springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://kodforum.us.auth0.com/
  flyway:
    locations: classpath:dbmigrations/
    enabled: true
    clean-disabled: false
    schemas: public
  datasource:
    driver-class-name: org.postgresql.Driver
    username: dbadmin
    url: jdbc:postgresql://localhost:5432/testdb
    password: dbadmin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 5
          order_inserts: true
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
        show_sql: false
    open-in-view: false

auth0:
  audience: api.kodforum.com
  domain: kodforum.us.auth0.com
  client-id: XXXXXXXXXX
  client-secret: XXXXXXXXX
  management-audience: https://kodforum.us.auth0.com/api/v2/
  issuer-uri: https://kodforum.us.auth0.com/
  user-database: Username-Password-Authentication