package com.kodizim.findaduck.error;

public enum ErrorCode {
    NOT_FOUND,
    ALREADY_EXISTS,
    VALIDATION,
    MAX_UPLOAD_SIZE_EXCEEDED,
    RATE_LIMIT_EXCEEDED,
    INVALID_PASSWORD_OR_EMAIL,
    USER_CAN_NOT_BE_DELETED,
    IN_PROGRESS, UNKNOWN
}
